config/routes.rb
Rails.application.routes.draw do
  root "bears#index"
  resources :bears

end

app/models/bear.rb
class Bear < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bears_controller.rb
class BearsController < ApplicationController
  def index
    @bears = Bear.all
  end

  def new
    @bear = Bear.new
  end

  def create
    @bear = Bear.new(bear_params)
    if @bear.save
      flash[:success] = "SUCESS! Bear created!"
      redirect_to bear_path(@bear.id)
    else
      flash[:error] = "ERROR: BEAR COULDN'T BE CREATED!"
      render :new
    end
  end

  def show
    @bear = Bear.find(params[:id])
  end

  def edit
    @bear = Bear.find(params[:id])
  end

  def update
    @bear = Bear.find(params[:id])
    if @bear.update(bear_params)
      flash[:success] = "Bear updated!"
      redirect_to bear_path(@bear.id)
    else
      flash[:error].now = "ERROR: BEAR COULDN'T BE UPDATED!"
      render :edit
    end
  end

  def destroy
    @bear = Bear.find(params[:id])
    if @bear.destroy
      flash[:success] = "Bear Deleted!"
      redirect_to bears_path
    else
      flash[:error] = "ERROR: BEAR COULDN'T BE DESTROYED!"
      redirect_to :index
    end
  end

  private

  def bear_params
    params.require(:bear).permit(:name, :description, :width, :height)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bears_helper.rb
module BearsHelper
end

app/views/bears/edit.html.erb
<h1>Edit this bear!</h1>
<p>Modify it's name, description, width, and height. Dimensions should be between 100 and 300 inclusive for safe measure.</p>

<%= form_for @bear do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>

  <%= f.label :description %>:
  <%= f.text_field :description %>

  <%= f.label :width %>:
  <%= f.text_field :width %>

  <%= f.label :height %>:
  <%= f.text_field :height %>

  <%= f.submit %>
<% end %>
<div>
  <img src="http://placebear.com/<%= @bear.width %>/<%= @bear.height %>" alt="<%= @bear.name %>">
</div>

app/views/bears/index.html.erb
<h1>Behold! This is the Index of all Bears!</h1>

<table>
  <tr>
    <th>Bear ID</th>
    <th>Bear Name</th>
    <th>Bear Width</th>
    <th>Bear Height</th>
    <th>Bear Description</th>
    <th>Bear Image</th>
    <th>Edit Bear</th>
    <th>Delete Bear</th>
  </tr>
  <% @bears.each do |bear| %>
    <tr>
      <td><%= bear.id %></td>
      <td><%= bear.name %></td>
      <td><%= bear.width %></td>
      <td><%= bear.height %></td>
      <td><%= bear.description %></td>
      <td><img src="http://placebear.com/<%= bear.width %>/<%= bear.height %>" alt="<%= bear.name %>"></td>
      <td><%= link_to "Edit this Bear!", edit_bear_path(bear.id) %></td>
      <td><%= link_to "Delete this Bear!", bear_path(bear.id), method: "delete" %></td>
    </tr>
  <% end %>
</table>

app/views/bears/new.html.erb
<h1>Create a new bear!</h1>
<p>Give it a name, description, a width, and a height with dimensions between 100 and 300 inclusive.</p>

<%= form_for @bear do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>

  <%= f.label :description %>:
  <%= f.text_field :description %>

  <%= f.label :width %>:
  <%= f.text_field :width %>

  <%= f.label :height %>:
  <%= f.text_field :height %>

  <%= f.submit %>
<% end %>

app/views/bears/show.html.erb
<h3>Say hi to <%= "#{@bear.name}!" %> </h3>
<p><%= "#{@bear.name} has a width of #{@bear.width} and a height of #{@bear.height}!"%></p>
<h2>Description</h2>
<p><%= @bear.description %></p>
<div>
  <img src="http://placebear.com/<%= @bear.width %>/<%= @bear.height %>" alt="<%= @bear.name %>">
</div>

<%= link_to "Edit this Bear!", edit_bear_path(@bear.id) %>
<%= link_to "Delete this Bear!", bear_path(@bear.id), method: "delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CruddyBearNecessities</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |type, message| %>
  <p class='<%= type %>'><%= "#{message}" %></div>
<% end %>

<%= render partial: 'shared/navbar' %>
<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<%= link_to "LINK TO INDEX", root_path %>
<%= link_to "CREATE A NEW BEAR!", new_bear_path %>